---
driver:
  name: vagrant
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[zookeeper_tester]

  - name: zookeeper_env
    run_list:
      - recipe[zookeeper_tester]
    attributes:
      zookeeper:
        env_vars:
          ZOO_LOG4J_PROP: 'INFO,ROLLINGFILE'
          ZOO_LOG_DIR: /var/log/zookeeper

  - name: sysv
    run_list:
      - recipe[zookeeper_tester]
    attributes:
      zookeeper:
        service_style: sysv
    includes:
      - centos-6.5

  - name: upstart
    run_list:
      - recipe[zookeeper_tester]
    attributes:
      zookeeper:
        service_style: upstart
    includes:
      - ubuntu-14.04
