---
driver:
  name: vagrant
  require_chef_omnibus: 11.8

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[zookeeper_tester]
    attributes:
