---
driver:
  name: dokken
  chef_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: false

verifier:
  name: inspec
  chef_license: accept

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
    attributes:
      java:
        jdk_version: '8'
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
    attributes:
      java:
        jdk_version: '8'
  - name: centos-7
    driver:
      image: dokken/centos-7
      platform: rhel
    attributes:
      java:
        jdk_version: '8'

suites:
  - name: default
    run_list:
      - recipe[zookeeper_tester]

  - name: attributes
    run_list:
      - recipe[zookeeper_tester::attributes]
    attributes:
      zookeeper:
        conf_dir: /etc/zookeeper/conf
        env_vars:
          ZOO_LOG4J_PROP: 'INFO,ROLLINGFILE'

  - name: systemd
    run_list:
      - recipe[zookeeper_tester::systemd]
    attributes:
      zookeeper:
        conf_dir: /etc/zookeeper/conf
