---
driver:
  name: vagrant
  require_chef_omnibus: 12.11

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
    attributes:
      java:
        jdk_version: 7
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[zookeeper_tester]

  - name: attributes
    run_list:
      - recipe[zookeeper_tester::attributes]
    attributes:
      zookeeper:
        env_vars:
          ZOO_LOG4J_PROP: 'INFO,ROLLINGFILE'

  - name: sysv
    run_list:
      - recipe[zookeeper_tester::sysv]
    includes:
      - centos-6.7

  - name: systemd
    run_list:
      - recipe[zookeeper_tester::systemd]
    includes:
      - ubuntu-16.04
      - centos-7.2

  - name: upstart
    run_list:
      - recipe[zookeeper_tester::upstart]
    includes:
      - ubuntu-14.04
