# Lining up the attributes of some methods is advantageous for readability
Style/SpaceBeforeFirstArg:
  Enabled: false

# Chef methods tend to be self-documenting
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/ClassVars:
  Exclude:
    - 'libraries/default.rb'

# The default 79 character limit is sometimes unproductive.
Metrics/LineLength:
  Max: 120

# The default 10 lines limit is unrealistic.
Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'vendor/bundle/**/*'
