name             'zookeeper'
maintainer       'Simple Finance Technology Corp.'
maintainer_email 'ops@simple.com'
license          'Apache v2.0'
description      'Installs/Configures zookeeper'
version          '2.4.3'

depends          'build-essential', '>= 2.0.2'
depends          'java'
depends          'runit'
