name             "zookeeper"
maintainer       "Simple Finance Technology Corp."
maintainer_email "mwhooker@simple.com"
license          "Apache v2.0"
description      "Installs/Configures zookeeper"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
depends          "java"
depends          "build-essential"
depends          "runit"
version          "1.5.1"
